# Generated by Django 5.1.2 on 2024-10-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('used_books', models.FloatField()),
                ('pages', models.PositiveIntegerField()),
                ('avg_reviews', models.FloatField()),
                ('n_reviews', models.CharField(max_length=200)),
                ('star5', models.CharField(max_length=5)),
                ('star4', models.CharField(max_length=5)),
                ('star3', models.CharField(max_length=5)),
                ('star2', models.CharField(max_length=5)),
                ('star1', models.CharField(max_length=5)),
                ('dimensions', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('ISBN_13', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('complete_link', models.CharField(max_length=200)),
            ],
        ),
    ]
